name: Update demo

on:
  push:
    branches:
      - main


permissions:
  contents: write # for create commit comment

jobs:
  update_demo:
    runs-on: ubuntu-latest
    # set variables
    env:
      BRANCH_TO_UPDATE: latest-copy
    steps:
    - name: Checkout click-app-copier
      uses: actions/checkout@v5
      with:
        path: main
    - name: Checkout click-app-copier-template-demo
      uses: actions/checkout@v5
      with:
        repository: kj-9/click-app-copier-template-demo
        path: click-app-copier-template-demo-current
        ref: ${{ env.BRANCH_TO_UPDATE }}
        token: ${{ secrets.PAT_WRITE_CLICK_APP_COPIER_TEMPLATE_DEMO }}
    - name: Set up Python
      uses: astral-sh/setup-uv@v6
      with:
        python-version: "3.13"
        enable-cache: true
    - name: Set up dependencies
      run: |-
        uv venv
        uv pip install -r main/requirements.txt
    - name: Build demo from template
      run: |-
        cat main/input-for-demo.txt | copier copy main click-app-copier-template-demo
        find click-app-copier-template-demo
        cd click-app-copier-template-demo && make sync ci-check
    - name: Push to git
      env:
        PERSONAL_ACCESS_TOKEN_FOR_PUSH: ${{ secrets.PAT_WRITE_CLICK_APP_COPIER_TEMPLATE_DEMO }}
      run: |-
        # Move the .git folder across
        mv click-app-copier-template-demo-current/.git click-app-copier-template-demo
        # Commit and push the changes
        cd click-app-copier-template-demo
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A .
        git commit -m "Demo of click-app ${GITHUB_SHA}" || exit 0
        git push -u origin ${{ env.BRANCH_TO_UPDATE }}
    - name: Post commit comment
      run: |-
        cd click-app-copier-template-demo
        export FULL_SHA=$(git rev-parse HEAD)
        export SHORT_SHA=${FULL_SHA::8}
        export NEWLINE=$'\n'
        echo '{}' | jq --arg v "Demo: https://github.com/kj-9/click-app-copier-template-demo/tree/$SHORT_SHA" \
          '. + { body: $v }' | \
        curl -sL  -X POST -d @- \
          -H "Content-Type: application/json" \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/$GITHUB_REPOSITORY/commits/$GITHUB_SHA/comments"
